name: bash
description: Wrapper over `dart:io` [Process] API's that supports additional features.
version: 2025.526.2354
homepage: 
repository: https://github.com/dart-pkg/bash
environment:
  sdk: ^3.7.2
platforms:
  android: 
  ios: 
  linux: 
  macos: 
  # web:
  windows: 
dependencies:
  file: ^7.0.1
  path: ^1.9.1
  process: ^5.0.4
  std: ^2025.526.2333
dev_dependencies:
  test: ^1.26.2
  lints: ^6.0.0
